In [10]:
import requests
import csv
import pandas as pd

def upload():
    try:
        line = ""
        f = open("data.csv", 'r')
        for tmp in f:
            line += tmp
            print(line)
        f.close()
        data = {'data': line}
        myUrl = 'http://wiffy.io/sen/upload.php'
        requests.post(myUrl, data=data).text
    except:
        print('ERROR')

def download():
    try:
        myUrl = 'http://wiffy.io/sen/data.csv'
        res = requests.post(myUrl).text
        
        sres = res.split("\n")
        f = open("data.csv", 'w')
        for tmp in sres:
            f.write(tmp + "\n")
        f.close()
    except:
        print('ERROR')

def delete():
    try:
        myUrl = 'http://wiffy.io/sen/delete.php'
        requests.post(myUrl).text
    except:
        print('ERROR')
        
list = ['2019-12-02 09:20:53.861315', 143, 126, 840, 453, 270]
download()
df = pd.read_csv("data.csv")
#df.loc[len(df)] = [n for n in list]
#df.to_csv("data.csv", index = False)
#df.to_csv("data.csv", mode='w', index = False)
#upload()
df

,time,Sensor1,Sensor2,Sensor3,Sensor4,Angle
0,11-01-23:19,163,163,47,32,90.000000
1,11-01-23:20,180,143,50,50,90.000000
2,11-01-23:21,167,73,32,32,90.000000
3,11-01-23:22,140,104,78,92,90.000000
4,11-01-23:23,32,109,96,48,270.000000
5,11-01-23:24,43,109,33,56,270.000000
6,11-01-23:25,50,109,27,49,270.000000
7,11-01-23:19,163,163,47,32,90.000000
8,11-01-23:20,180,143,50,50,90.000000
9,11-01-23:21,167,73,32,32,90.000000
10,11-01-23:22,140,104,78,92,90.000000
11,11-01-23:23,32,109,96,48,270.000000
12,11-01-23:24,43,109,33,56,270.000000
13,11-01-23:25,50,109,27,49,270.000000
14,11-01-23:19,163,163,47,32,90.000000
15,11-01-23:20,180,143,50,50,90.000000
16,11-01-23:21,167,73,32,32,90.000000
17,11-01-23:22,140,104,78,92,90.000000
18,11-01-23:23,32,109,96,48,270.000000
19,11-01-23:24,43,109,33,56,270.000000
20,11-01-23:25,50,109,27,49,270.000000
21,11-01-23:19,163,163,47,32,90.000000
22,11-01-23:20,180,143,50,50,90.000000
23,11-01-23:21,167,73,32,32,90.000000
24,11-01-23:22,140,104,78,92,90.000000
25,11-01-23:23,32,109,96,48,270.000000
26,11-01-23:24,43,109,33,56,270.000000
27,11-01-23:25,50,109,27,49,270.000000
28,11-01-23:19,163,163,47,32,90.000000
29,11-01-23:20,180,143,50,50,90.000000
...,...,...,...,...,...,...
90,11-01-23:25,50,109,27,49,270.000000
91,11-01-23:19,163,163,47,32,90.000000
92,11-01-23:20,180,143,50,50,90.000000
93,11-01-23:21,167,73,32,32,90.000000
94,11-01-23:22,140,104,78,92,90.000000
95,11-01-23:23,32,109,96,48,270.000000
96,11-01-23:24,43,109,33,56,270.000000
97,11-01-23:25,50,109,27,49,270.000000
98,11-01-23:19,163,163,47,32,90.000000
99,11-01-23:20,180,143,50,50,90.000000
100,11-01-23:21,167,73,32,32,90.000000
101,11-01-23:22,140,104,78,92,90.000000
102,11-01-23:23,32,109,96,48,270.000000
103,11-01-23:24,43,109,33,56,270.000000
104,11-01-23:25,50,109,27,49,270.000000
105,11-01-23:19,163,163,47,32,90.000000
106,11-01-23:20,180,143,50,50,90.000000
107,11-01-23:21,167,73,32,32,90.000000
108,11-01-23:22,140,104,78,92,90.000000
109,11-01-23:23,32,109,96,48,270.000000
110,11-01-23:24,43,109,33,56,270.000000
111,11-01-23:25,50,109,27,49,266.665814
112,2019-12-02 08:32:48.152336,105,105,105,105,90.000000
113,2019-12-02 08:49:18.085075,109,109,109,109,90.000000
114,2019-12-02 09:01:47.167847,115,115,115,115,90.000000
115,2019-12-02 09:02:45.381582,116,116,116,116,90.000000
116,2019-12-02 09:03:09.577747,116,116,116,116,90.000000
117,2019-12-02 09:03:56.799545,116,116,116,116,90.000000
118,2019-12-02 09:20:53.861315,143,143,143,143,37.521656
119,2019-12-02 09:20:53.861315,143,126,840,453,-420.418767